'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

// 创建一个类型安全的索引签名
interface Translations {
  [key: string]: string;
}

interface TranslationSet {
  zh: Translations;
  en: Translations;
}

const translations: TranslationSet = {
  zh: {
    // 通用
    'language': '语言',
    'chinese': '中文',
    'english': '英文',
    
    // 首页
    'oms.title': '订单管理系统',
    'oms.subtitle': '高效管理订单处理和库存跟踪',
    'order.management': '订单管理',
    'order.management.desc': '查看、处理和跟踪所有客户订单。',
    'view.orders': '查看订单',
    'dashboard': '数据统计',
    'dashboard.desc': '通过实时分析获取业务洞察。',
    'view.dashboard': '查看统计',
    'quick.stats': '快速统计',
    'pending.orders': '待处理订单',
    'completed.today': '今日完成',
    'total.revenue': '总收入',
    'avg.processing.time': '平均处理时间',
    'days': '天',
    
    // 订单列表页
    'orders': '订单',
    'filter': '筛选',
    'new.order': '新订单',
    'order.id': '订单编号',
    'customer': '客户',
    'date': '日期',
    'total': '总计',
    'actions': '操作',
    'view': '查看',
    'edit': '编辑',
    'showing': '显示',
    'to': '到',
    'of': '共',
    'results': '条结果',
    'previous': '上一页',
    'next': '下一页',
    
    // 订单状态
    'status.completed': '已完成',
    'status.processing': '处理中',
    'status.pending': '待处理',
    'status.shipped': '已发货',
    
    // 订单详情页
    'back.to.orders': '返回订单列表',
    'order': '订单',
    'print': '打印',
    'update.status': '更新状态',
    'customer.info': '客户信息',
    'shipping.address': '收货地址',
    'order.summary': '订单摘要',
    'payment.method': '支付方式',
    'shipping.method': '配送方式',
    'order.items': '订单商品',
    'product': '商品',
    'quantity': '数量',
    'price': '单价',
    'subtotal': '小计',
    'shipping': '运费',
    'tax': '税费',
    'notes': '备注',
    'search.orders': '订单查询',
    'search': '搜索',
    'reset': '重置',
    'search.by.order.id': '按订单编号搜索',
    'search.by.customer': '按客户名称搜索',
    'customer.name': '客户名称',
    'start.date': '开始日期',
    'end.date': '结束日期',
    'all.statuses': '所有状态',
    'no.results': '没有找到匹配的订单',
    'items.per.page': '每页显示',
    'dashboard.overview': '业务概览和关键指标',
    'total.orders': '总订单数',
    'from.last.month': '相比上月',
    'avg.order.value': '平均订单金额',
    'conversion.rate': '转化率',
    'sales.trend': '销售趋势 (30天)',
    'order.status.distribution': '订单状态分布',
    'recent.orders': '最近订单',
    'view.all': '查看全部',
    'performance.metrics': '性能指标',
    'return.rate': '退货率',
    'customer.satisfaction': '客户满意度',
    'home': '首页',
    'products': '产品管理',
    'customers': '客户管理',
    'coming.soon': '即将推出',
    'products.coming.soon': '产品管理功能即将推出',
    'customers.coming.soon': '客户管理功能即将推出',
    'products.page.description': '产品管理功能正在开发中，敬请期待。您将能够添加、编辑和管理所有产品信息。',
    'customers.page.description': '客户管理功能正在开发中，敬请期待。您将能够查看客户信息、订单历史和管理客户关系。',
    'channel': '渠道',
    'channel.all': '所有渠道',
    'channel.xiaohongshu': '小红书',
    'channel.jd': '京东',
    'channel.taobao': '淘宝',
    'channel.douyin': '抖音',
    'channel.wechat': '微信小程序',
    'channel.offline': '线下门店',
    'channel.other': '其他渠道',
    'filter.by.channel': '按渠道筛选',
    'channel.analysis': '渠道分析',
    'top.channels': '热门渠道',
    
    // 产品管理相关翻译
    'product.management': '产品管理',
    'product.id': '产品编号',
    'product.name': '产品名称',
    'product.details': '产品详情',
    'product.image': '产品图片',
    'category': '分类',
    'stock': '库存',
    'sku': 'SKU',
    'status': '状态',
    'status.product': '产品状态',
    'description': '描述',
    'description.product': '产品描述',
    'actions': '操作',
    'actions.product': '产品操作',
    
    // 产品筛选相关
    'filter.products': '筛选产品',
    'filters.active': '筛选已应用',
    'results.found': '个结果',
    'enter.product.id': '输入产品编号',
    'enter.product.name': '输入产品名称',
    'min.price': '最低价格',
    'max.price': '最高价格',
    'enter.min.price': '输入最低价格',
    'enter.max.price': '输入最高价格',
    'apply.filters': '应用筛选',
    'reset.filters': '清除筛选',
    'no.products.found': '未找到符合条件的产品',
    
    // 产品分类
    'category.all': '所有分类',
    'category.handbag': '手提包',
    'category.tote': '托特包',
    'category.shoulder': '单肩包',
    'category.crossbody': '斜挎包',
    'category.wallet': '钱包',
    'category.footwear': '鞋履',
    'category.accessories': '配饰',
    
    // 产品状态
    'status.all': '所有状态',
    'status.active': '在售',
    'status.outofstock': '缺货',
    'status.preorder': '预售',
    'status.discontinued': '停产',
    
    // 产品管理功能
    'add.product': '添加产品',
    'edit.product': '编辑产品',
    'delete.product': '删除产品',
    'view.product': '查看产品',
    'import.products': '导入产品',
    'export.products': '导出产品',
    'bulk.actions': '批量操作',
    'low.stock.alert': '库存不足警报',
    'low.stock.alert.threshold': '库存不足警报阈值',
    'out.of.stock': '缺货产品',
    'left': '剩余',
    'restock': '补货',
    'view.all.products': '查看所有产品',
    'inventory.management': '库存管理',
    'inventory.management.desc': '管理全渠道库存，包括线上和线下库存',
    'all.inventory': '全部库存',
    'online.inventory': '线上库存',
    'offline.inventory': '线下库存',
    'filter.inventory': '筛选库存',
    'inventory.summary': '库存概览',
    'total.products': '产品总数',
    'total.inventory.value': '库存总价值',
    'online.stock.value': '线上库存价值',
    'offline.stock.value': '线下库存价值',
    'inventory.alerts': '库存警报',
    'out.of.stock.alert': '缺货警报',
    'inventory.transfer.needed': '需要调拨',
    'products.low.stock': '个产品库存不足',
    'products.out.of.stock': '个产品缺货',
    'products.need.transfer': '个产品需要调拨',
    'recent.inventory.activity': '最近库存活动',
    'stock.received': '入库',
    'stock.transferred': '调拨',
    'stock.adjusted': '调整',
    'received.items': '收到 {count} 件商品',
    'transferred.items': '从{from}调拨 {count} 件商品到{to}',
    'adjusted.items': '因{reason}调整 {count} 件商品',
    'inventory.count': '盘点',
    'view.all.activity': '查看所有活动',
    'all.locations': '所有位置',
    'online.warehouse': '线上仓库',
    'beijing.flagship.store': '北京旗舰店',
    'shanghai.store': '上海店',
    'guangzhou.store': '广州店',
    'shenzhen.store': '深圳店',
    'add.inventory': '添加库存',
    'import.inventory': '导入库存',
    'export.inventory': '导出库存',
    'inventory.report': '库存报表',
    'manage.alerts': '管理警报',
    'enter.sku': '输入SKU',
    'location': '位置',
    'stock.status': '库存状态',
    'stock.status.all': '所有状态',
    'stock.status.in': '库存充足',
    'stock.status.low': '库存不足',
    'stock.status.out': '缺货',
    'total.stock': '总库存',
    'available.stock': '可用库存',
    'reserved.stock': '预留库存',
    'locations': '位置',
    'last.updated': '最后更新',
    'view': '查看',
    'view.details': '查看详情',
    'adjust': '调整',
    'transfer': '调拨',
    'no.inventory.found': '未找到符合条件的库存',
    'expand': '展开',
    'collapse': '收起',
    'view.inventory': '查看库存',
    'inventory': '库存',
    'channel.inventory.analysis': '渠道库存分析',
    'inventory.distribution': '库存分布',
    'channel.performance': '渠道表现',
    'chart.placeholder': '图表加载中...',
    'channel.sync.status': '渠道同步状态',
    'last.sync': '最后同步时间',
    'sync.status': '同步状态',
    'sync.success': '同步成功',
    'sync.partial': '部分同步',
    'sync.failed': '同步失败',
    'sync.now': '立即同步',
    'sync': '同步',
    'allocate.inventory': '分配库存',
    'set.channel.thresholds': '设置渠道阈值',
    'channel.inventory.report': '渠道库存报表',
    'channel.online': '线上渠道',
    'inventory.distribution.by.channel': '各渠道库存分布',
    'inventory.trend.by.channel': '各渠道库存趋势',
    'inventory.turnover.rate': '库存周转率',
    'inventory.turnover.rate.annual': '年周转率',
    'inventory.efficiency': '库存效率',
    'avg.days.in.inventory': '平均库存天数',
    'inventory.accuracy': '库存准确率',
    'stockout.rate': '缺货率',
    'inventory.insights': '库存洞察',
    'inventory.insight.1': '淘宝渠道库存周转率高于平均水平，建议增加库存分配',
    'inventory.insight.2': '小红书渠道库存过高，建议调整库存分配策略',
    'inventory.insight.3': '线下门店库存周转率低，建议减少库存分配',
    'inventory.insight.4': '京东渠道库存趋势上升，预计未来需求增加',
    'inventory.overview': '库存概览',
    'inventory.list': '库存列表',
    'channel.management': '渠道管理',
    'inventory.activity': '库存活动',
    'in.stock.products': '有库存产品',
    'low.stock.products': '库存不足产品',
    'out.of.stock.products': '缺货产品',
    'inventory.details': '库存详情',
    'channel.distribution': '渠道分布',
    'from': '从',
    'to': '到',
    'close': '关闭',
    'current.stock': '当前库存',
    'adjustment.quantity': '调整数量',
    'use.positive.for.increase': '使用正数增加库存，负数减少库存',
    'adjustment.reason': '调整原因',
    'select.reason': '选择原因',
    'reason.damaged': '损坏',
    'reason.lost': '丢失',
    'reason.found': '找回',
    'reason.count': '盘点',
    'reason.return': '退货',
    'reason.other': '其他',
    'enter.notes': '输入备注',
    'cancel': '取消',
    'save': '保存',
    'quantity.required': '请输入数量',
    'reason.required': '请选择原因',
    'transfer.inventory': '调拨库存',
    'source.location': '源位置',
    'transfer.quantity': '调拨数量',
    'destination.location': '目标位置',
    'select.destination': '选择目标位置',
    'invalid.quantity': '无效的数量',
    'destination.required': '请选择目标位置',
    'adjust.inventory': '调整库存',
    'view.inventory': '查看库存',
    'type': '类型',
    'details': '详情',
    'user': '用户',
    'stock.received': '入库',
    'stock.adjusted': '调整',
    'stock.transferred': '调拨',
    'channel.details': '渠道详情',
    'channel.information': '渠道信息',
    'channel.id': '渠道ID',
    'channel.type': '渠道类型',
    'channel.statistics': '渠道统计',
    'product.count': '产品数量',
    'order.count': '订单数量',
    'revenue': '收入',
    'avg.order.value': '平均订单金额',
    'inventory.trend': '库存趋势',
    'inventory.level': '库存水平',
    'sales.trend': '销售趋势',
    'sales': '销售额',
    'inventory.trend.by.month': '月度库存趋势',
    'sales.trend.by.month': '月度销售趋势',
    'loading.data': '加载数据中...',
    'recent.activity': '最近活动',
    'activity': '活动',
    'sync.completed': '同步完成',
    'sync.products.inventory': '同步产品库存',
    'order.received': '收到订单',
    'product.updated': '产品更新',
    'sync.channel': '同步渠道',
    'select.sync.options': '选择同步选项',
    'sync.products': '同步产品',
    'sync.inventory': '同步库存',
    'sync.orders': '同步订单',
    'sync.prices': '同步价格',
    'select.at.least.one.option': '请至少选择一个选项',
    'sync.started': '同步已开始',
    'syncing.products': '正在同步产品...',
    'syncing.inventory': '正在同步库存...',
    'syncing.orders': '正在同步订单...',
    'syncing.prices': '正在同步价格...',
    'status.active': '活跃',
    'status.inactive': '不活跃',
    'status.pending': '待处理',
    'channel.allocation': '渠道分配',
    'channel.thresholds': '渠道阈值',
    'channel.thresholds.desc': '设置各渠道的库存阈值和警报级别',
    'channel.inventory.report': '渠道库存报告',
    'channel.inventory.report.desc': '查看各渠道的库存状态和分布情况',
    'channel.performance': '渠道表现',
    'channel.performance.desc': '分析各渠道的销售表现和转化率',
    'channel.settings': '渠道设置',
    'channel.settings.desc': '管理渠道连接和同步设置',
    'channel.integration': '渠道集成',
    'channel.integration.desc': '配置与外部销售渠道的集成',
    'channel.mapping': '渠道映射',
    'channel.mapping.desc': '设置产品和类别在各渠道的映射关系',
    'channel.pricing': '渠道定价',
    'channel.pricing.desc': '管理各渠道的产品定价策略',
    'channel.promotion': '渠道促销',
    'channel.promotion.desc': '设置和管理各渠道的促销活动',
    'channel.analytics': '渠道分析',
    'channel.analytics.desc': '深入分析各渠道的业务数据',
    'channel.comparison': '渠道对比',
    'channel.comparison.desc': '对比不同渠道的表现和效率',
    'channel.forecast': '渠道预测',
    'channel.forecast.desc': '基于历史数据预测各渠道的销售趋势',
    'channel.optimization': '渠道优化',
    'channel.optimization.desc': '优化渠道策略以提高整体业绩',
    'sync.status.report': '同步状态报告',
    'sync.history': '同步历史',
    'sync.schedule': '同步计划',
    'sync.settings': '同步设置',
    'sync.frequency': '同步频率',
    'sync.hourly': '每小时',
    'sync.daily': '每天',
    'sync.weekly': '每周',
    'sync.manual': '手动',
    'sync.auto': '自动',
    'sync.last.attempt': '上次同步尝试',
    'sync.next.scheduled': '下次计划同步',
    'sync.error.details': '错误详情',
    'sync.retry': '重试同步',
    'sync.cancel': '取消同步',
    'sync.pause': '暂停同步',
    'sync.resume': '恢复同步',
  },
  en: {
    // General
    'language': 'Language',
    'chinese': 'Chinese',
    'english': 'English',
    
    // Home page
    'oms.title': 'Order Management System',
    'oms.subtitle': 'Efficiently manage order processing and inventory tracking',
    'order.management': 'Order Management',
    'order.management.desc': 'View, process, and track all customer orders.',
    'view.orders': 'View Orders',
    'dashboard': 'Dashboard',
    'dashboard.desc': 'Get business insights through real-time analytics.',
    'view.dashboard': 'View Dashboard',
    'quick.stats': 'Quick Stats',
    'pending.orders': 'Pending Orders',
    'completed.today': 'Completed Today',
    'total.revenue': 'Total Revenue',
    'avg.processing.time': 'Avg. Processing Time',
    'days': 'days',
    
    // Orders list page
    'orders': 'Orders',
    'filter': 'Filter',
    'new.order': 'New Order',
    'order.id': 'Order ID',
    'customer': 'Customer',
    'date': 'Date',
    'total': 'Total',
    'actions': 'Actions',
    'view': 'View',
    'edit': 'Edit',
    'showing': 'Showing',
    'to': 'to',
    'of': 'of',
    'results': 'results',
    'previous': 'Previous',
    'next': 'Next',
    
    // Order statuses
    'status.completed': 'Completed',
    'status.processing': 'Processing',
    'status.pending': 'Pending',
    'status.shipped': 'Shipped',
    
    // Order details page
    'back.to.orders': 'Back to Orders',
    'order': 'Order',
    'print': 'Print',
    'update.status': 'Update Status',
    'customer.info': 'Customer Information',
    'shipping.address': 'Shipping Address',
    'order.summary': 'Order Summary',
    'payment.method': 'Payment Method',
    'shipping.method': 'Shipping Method',
    'order.items': 'Order Items',
    'product': 'Product',
    'quantity': 'Quantity',
    'price': 'Price',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'tax': 'Tax',
    'notes': 'Notes',
    'search.orders': 'Search Orders',
    'search': 'Search',
    'reset': 'Reset',
    'search.by.order.id': 'Search by order ID',
    'search.by.customer': 'Search by customer name',
    'customer.name': 'Customer Name',
    'start.date': 'Start Date',
    'end.date': 'End Date',
    'all.statuses': 'All Statuses',
    'no.results': 'No matching orders found',
    'items.per.page': 'Items per page',
    'dashboard.overview': 'Business overview and key metrics',
    'total.orders': 'Total Orders',
    'from.last.month': 'from last month',
    'avg.order.value': 'Avg. Order Value',
    'conversion.rate': 'Conversion Rate',
    'sales.trend': 'Sales Trend (30 days)',
    'order.status.distribution': 'Order Status Distribution',
    'recent.orders': 'Recent Orders',
    'view.all': 'View All',
    'performance.metrics': 'Performance Metrics',
    'return.rate': 'Return Rate',
    'customer.satisfaction': 'Customer Satisfaction',
    'home': 'Home',
    'products': 'Products',
    'customers': 'Customers',
    'coming.soon': 'Coming Soon',
    'products.coming.soon': 'Product management features coming soon',
    'customers.coming.soon': 'Customer management features coming soon',
    'products.page.description': 'Product management features are under development. You will be able to add, edit, and manage all product information.',
    'customers.page.description': 'Customer management features are under development. You will be able to view customer information, order history, and manage customer relationships.',
    'channel': 'Channel',
    'channel.all': 'All Channels',
    'channel.xiaohongshu': 'Xiaohongshu',
    'channel.jd': 'JD.com',
    'channel.taobao': 'Taobao',
    'channel.douyin': 'Douyin',
    'channel.wechat': 'WeChat Mini Program',
    'channel.offline': 'Offline Store',
    'channel.other': 'Other Channels',
    'filter.by.channel': 'Filter by Channel',
    'channel.analysis': 'Channel Analysis',
    'top.channels': 'Top Channels',
    
    // 产品管理相关翻译
    'product.management': 'Product Management',
    'product.id': 'Product ID',
    'product.name': 'Product Name',
    'product.details': 'Product Details',
    'product.image': 'Product Image',
    'category': 'Category',
    'stock': 'Stock',
    'sku': 'SKU',
    'status': 'Status',
    'status.product': 'Product Status',
    'description': 'Description',
    'description.product': 'Product Description',
    'actions': 'Actions',
    'actions.product': 'Product Actions',
    
    // 产品筛选相关
    'filter.products': 'Filter Products',
    'filters.active': 'Filters Applied',
    'results.found': 'results found',
    'enter.product.id': 'Enter product ID',
    'enter.product.name': 'Enter product name',
    'min.price': 'Min Price',
    'max.price': 'Max Price',
    'enter.min.price': 'Enter minimum price',
    'enter.max.price': 'Enter maximum price',
    'apply.filters': 'Apply Filters',
    'reset.filters': 'Clear Filters',
    'no.products.found': 'No products found matching your criteria',
    
    // 产品分类
    'category.all': 'All Categories',
    'category.handbag': 'Handbags',
    'category.tote': 'Tote Bags',
    'category.shoulder': 'Shoulder Bags',
    'category.crossbody': 'Crossbody Bags',
    'category.wallet': 'Wallets',
    'category.footwear': 'Footwear',
    'category.accessories': 'Accessories',
    
    // 产品状态
    'status.all': 'All Statuses',
    'status.active': 'Active',
    'status.outofstock': 'Out of Stock',
    'status.preorder': 'Pre-order',
    'status.discontinued': 'Discontinued',
    
    // 产品管理功能
    'add.product': 'Add Product',
    'edit.product': 'Edit Product',
    'delete.product': 'Delete Product',
    'view.product': 'View Product',
    'import.products': 'Import Products',
    'export.products': 'Export Products',
    'bulk.actions': 'Bulk Actions',
    'low.stock.alert': 'Low Stock Alert',
    'low.stock.alert.threshold': 'Low Stock Alert Threshold',
    'out.of.stock': 'Out of Stock',
    'left': 'left',
    'restock': 'Restock',
    'view.all.products': 'View All Products',
    'inventory.management': 'Inventory Management',
    'inventory.management.desc': 'Manage omnichannel inventory including online and offline stock',
    'all.inventory': 'All Inventory',
    'online.inventory': 'Online Inventory',
    'offline.inventory': 'Offline Inventory',
    'filter.inventory': 'Filter Inventory',
    'inventory.summary': 'Inventory Summary',
    'total.products': 'Total Products',
    'total.inventory.value': 'Total Inventory Value',
    'online.stock.value': 'Online Stock Value',
    'offline.stock.value': 'Offline Stock Value',
    'inventory.alerts': 'Inventory Alerts',
    'out.of.stock.alert': 'Out of Stock Alert',
    'inventory.transfer.needed': 'Inventory Transfer Needed',
    'products.low.stock': '{count} Products Low on Stock',
    'products.out.of.stock': '{count} Products Out of Stock',
    'products.need.transfer': '{count} Products Need Transfer',
    'recent.inventory.activity': 'Recent Inventory Activity',
    'stock.received': 'Stock Received',
    'stock.transferred': 'Stock Transferred',
    'stock.adjusted': 'Stock Adjusted',
    'received.items': 'Received {count} items',
    'transferred.items': 'Transferred {count} items from {from} to {to}',
    'adjusted.items': 'Adjusted {count} items due to {reason}',
    'inventory.count': 'Inventory Count',
    'view.all.activity': 'View All Activity',
    'all.locations': 'All Locations',
    'online.warehouse': 'Online Warehouse',
    'beijing.flagship.store': 'Beijing Flagship Store',
    'shanghai.store': 'Shanghai Store',
    'guangzhou.store': 'Guangzhou Store',
    'shenzhen.store': 'Shenzhen Store',
    'add.inventory': 'Add Inventory',
    'import.inventory': 'Import Inventory',
    'export.inventory': 'Export Inventory',
    'inventory.report': 'Inventory Report',
    'manage.alerts': 'Manage Alerts',
    'enter.sku': 'Enter SKU',
    'location': 'Location',
    'stock.status': 'Stock Status',
    'stock.status.all': 'All Statuses',
    'stock.status.in': 'In Stock',
    'stock.status.low': 'Low Stock',
    'stock.status.out': 'Out of Stock',
    'total.stock': 'Total Stock',
    'available.stock': 'Available Stock',
    'reserved.stock': 'Reserved Stock',
    'locations': 'Locations',
    'last.updated': 'Last Updated',
    'view': 'View',
    'view.details': 'View Details',
    'adjust': 'Adjust',
    'transfer': 'Transfer',
    'no.inventory.found': 'No inventory found matching your criteria',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'view.inventory': 'View Inventory',
    'inventory': 'Inventory',
    'channel.inventory.analysis': 'Channel Inventory Analysis',
    'inventory.distribution': 'Inventory Distribution',
    'channel.performance': 'Channel Performance',
    'chart.placeholder': 'Chart loading...',
    'channel.sync.status': 'Channel Sync Status',
    'last.sync': 'Last Sync',
    'sync.status': 'Sync Status',
    'sync.success': 'Sync Success',
    'sync.partial': 'Partial Sync',
    'sync.failed': 'Sync Failed',
    'sync.now': 'Sync Now',
    'sync': 'Sync',
    'allocate.inventory': 'Allocate Inventory',
    'set.channel.thresholds': 'Set Channel Thresholds',
    'channel.inventory.report': 'Channel Inventory Report',
    'channel.online': 'Online Channel',
    'inventory.distribution.by.channel': 'Inventory Distribution by Channel',
    'inventory.trend.by.channel': 'Inventory Trend by Channel',
    'inventory.turnover.rate': 'Inventory Turnover Rate',
    'inventory.turnover.rate.annual': 'Annual Turnover Rate',
    'inventory.efficiency': 'Inventory Efficiency',
    'avg.days.in.inventory': 'Avg. Days in Inventory',
    'inventory.accuracy': 'Inventory Accuracy',
    'stockout.rate': 'Stockout Rate',
    'inventory.insights': 'Inventory Insights',
    'inventory.insight.1': 'Taobao channel turnover rate is above average, consider increasing allocation',
    'inventory.insight.2': 'Xiaohongshu channel inventory is too high, consider adjusting allocation strategy',
    'inventory.insight.3': 'Offline stores have low turnover rate, consider reducing inventory allocation',
    'inventory.insight.4': 'JD.com channel inventory trend is rising, anticipate increased demand',
    'inventory.overview': 'Inventory Overview',
    'inventory.list': 'Inventory List',
    'channel.management': 'Channel Management',
    'inventory.activity': 'Inventory Activity',
    'in.stock.products': 'In Stock Products',
    'low.stock.products': 'Low Stock Products',
    'out.of.stock.products': 'Out of Stock Products',
    'inventory.details': 'Inventory Details',
    'channel.distribution': 'Channel Distribution',
    'from': 'From',
    'to': 'To',
    'close': 'Close',
    'current.stock': 'Current Stock',
    'adjustment.quantity': 'Adjustment Quantity',
    'use.positive.for.increase': 'Use positive numbers to increase stock, negative to decrease',
    'adjustment.reason': 'Adjustment Reason',
    'select.reason': 'Select Reason',
    'reason.damaged': 'Damaged',
    'reason.lost': 'Lost',
    'reason.found': 'Found',
    'reason.count': 'Inventory Count',
    'reason.return': 'Return',
    'reason.other': 'Other',
    'enter.notes': 'Enter notes',
    'cancel': 'Cancel',
    'save': 'Save',
    'quantity.required': 'Quantity is required',
    'reason.required': 'Reason is required',
    'transfer.inventory': 'Transfer Inventory',
    'source.location': 'Source Location',
    'transfer.quantity': 'Transfer Quantity',
    'destination.location': 'Destination Location',
    'select.destination': 'Select Destination',
    'invalid.quantity': 'Invalid quantity',
    'destination.required': 'Destination is required',
    'adjust.inventory': 'Adjust Inventory',
    'view.inventory': 'View Inventory',
    'type': 'Type',
    'details': 'Details',
    'user': 'User',
    'stock.received': 'Received',
    'stock.adjusted': 'Adjusted',
    'stock.transferred': 'Transferred',
    'channel.details': 'Channel Details',
    'channel.information': 'Channel Information',
    'channel.id': 'Channel ID',
    'channel.type': 'Channel Type',
    'channel.statistics': 'Channel Statistics',
    'product.count': 'Product Count',
    'order.count': 'Order Count',
    'revenue': 'Revenue',
    'avg.order.value': 'Avg. Order Value',
    'inventory.trend': 'Inventory Trend',
    'inventory.level': 'Inventory Level',
    'sales.trend': 'Sales Trend',
    'sales': 'Sales',
    'inventory.trend.by.month': 'Inventory Trend by Month',
    'sales.trend.by.month': 'Sales Trend by Month',
    'loading.data': 'Loading data...',
    'recent.activity': 'Recent Activity',
    'activity': 'Activity',
    'sync.completed': 'Sync Completed',
    'sync.products.inventory': 'Sync Products Inventory',
    'order.received': 'Order Received',
    'product.updated': 'Product Updated',
    'sync.channel': 'Sync Channel',
    'select.sync.options': 'Select Sync Options',
    'sync.products': 'Sync Products',
    'sync.inventory': 'Sync Inventory',
    'sync.orders': 'Sync Orders',
    'sync.prices': 'Sync Prices',
    'select.at.least.one.option': 'Please select at least one option',
    'sync.started': 'Sync started',
    'syncing.products': 'Syncing products...',
    'syncing.inventory': 'Syncing inventory...',
    'syncing.orders': 'Syncing orders...',
    'syncing.prices': 'Syncing prices...',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
    'status.pending': 'Pending',
    'channel.allocation': 'Channel Allocation',
    'channel.thresholds': 'Channel Thresholds',
    'channel.thresholds.desc': 'Set inventory thresholds and alert levels for each channel',
    'channel.inventory.report': 'Channel Inventory Report',
    'channel.inventory.report.desc': 'View inventory status and distribution across channels',
    'channel.performance': 'Channel Performance',
    'channel.performance.desc': 'Analyze sales performance and conversion rates by channel',
    'channel.settings': 'Channel Settings',
    'channel.settings.desc': 'Manage channel connections and synchronization settings',
    'channel.integration': 'Channel Integration',
    'channel.integration.desc': 'Configure integration with external sales channels',
    'channel.mapping': 'Channel Mapping',
    'channel.mapping.desc': 'Set up product and category mapping across channels',
    'channel.pricing': 'Channel Pricing',
    'channel.pricing.desc': 'Manage pricing strategies for products across channels',
    'channel.promotion': 'Channel Promotions',
    'channel.promotion.desc': 'Set up and manage promotional activities across channels',
    'channel.analytics': 'Channel Analytics',
    'channel.analytics.desc': 'Deep dive into business data across channels',
    'channel.comparison': 'Channel Comparison',
    'channel.comparison.desc': 'Compare performance and efficiency across different channels',
    'channel.forecast': 'Channel Forecast',
    'channel.forecast.desc': 'Forecast sales trends by channel based on historical data',
    'channel.optimization': 'Channel Optimization',
    'channel.optimization.desc': 'Optimize channel strategy to improve overall performance',
    'sync.status.report': 'Sync Status Report',
    'sync.history': 'Sync History',
    'sync.schedule': 'Sync Schedule',
    'sync.settings': 'Sync Settings',
    'sync.frequency': 'Sync Frequency',
    'sync.hourly': 'Hourly',
    'sync.daily': 'Daily',
    'sync.weekly': 'Weekly',
    'sync.manual': 'Manual',
    'sync.auto': 'Automatic',
    'sync.last.attempt': 'Last Sync Attempt',
    'sync.next.scheduled': 'Next Scheduled Sync',
    'sync.error.details': 'Error Details',
    'sync.retry': 'Retry Sync',
    'sync.cancel': 'Cancel Sync',
    'sync.pause': 'Pause Sync',
    'sync.resume': 'Resume Sync',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    // 从本地存储中获取语言设置，如果没有则使用默认值
    try {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'zh' || savedLanguage === 'en')) {
        setLanguageState(savedLanguage);
      }
    } catch (error) {
      // 如果localStorage不可用，使用默认语言
      console.error('Error accessing localStorage:', error);
    }
  }, []);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    try {
      localStorage.setItem('language', newLanguage);
    } catch (error) {
      console.error('Error writing to localStorage:', error);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 